from django.urls import path
from .views import *

app_name='accounts'


urlpatterns=[
    path('export-email', export_email_csv, name='export_email_csv'),
    path('export-phone', export_phone_csv, name='export_phone_csv'),
    path('export', export_users_csv, name='export_users_csv'),
    path('export-ref', export_ref_csv, name='export_ref_csv'),
    path('export-paid', export_paid_users_csv, name='export_paid_csv'),
    path('message-user/<pk>', messageCustomer, name="message"),
    path('referrals/<int:pk>', referrals, name='referrals'),
    path('<int:pk>', customer, name='customer'),
    path('make-admin/<int:pk>', makeAdmin, name='makeAdmin'),
    path('remove-admin/<int:pk>', removeAdmin, name='removeAdmin'),
    path('contributions', orders, name='orders'),
    path('topups', topups, name='topups'),
    path('compound-topups', ctopups, name='ctopups'),
    path('simple', simples, name='simples'),
    path('compounds', compounds, name='compounds'),
    path('loans', loans, name='loans'),
    path('members', customers, name='members'),
    path('approve-payouts', approve_payouts, name="approve-payouts"),
    path('approve-refpayouts', approve_refpayouts, name="approve-refpayouts"),
    path('due-payouts', payouts, name='payouts'),
    path('ref-payouts', refpayouts, name='refpayouts'),
    path('payouts', all_payouts, name='all-payouts'),
    path('refpayouts', all_refpayouts, name='all-refpayouts'),
    path('<int:pk>/order', order, name='order'),
    path('update/<pk>/<int:c_pk>', update_order, name='update'),
    path('update-simple/<pk>/<int:c_pk>', update_simple, name='update-simple'),
    path('update-compound/<pk>/<int:c_pk>', update_compound, name='update-compound'),
    path('update-simple-topup/<pk>/<int:c_pk>', update_Stopup, name='updateS'),
    path('update-compound-topup/<pk>/<int:c_pk>', update_Ctopup, name='updateC'),
    path('update-payout/<pk>/<int:c_pk>', update_payout, name='update-payout'),
    path('delete-payout/<pk>', delete_payout, name='delete-payout'),
    path('update-ref/<pk>/<int:c_pk>', update_refpayout, name='update-refpayout'),
    path('delete-ref/<pk>', delete_refpayout, name='delete-refpayout'),
    path('update-loan/<pk>/<int:c_pk>', update_loan, name='update-loan'),
    path('delete-loan/<pk>', delete_loan, name='delete-loan'),
    path('delete-user/<pk>', remove_user, name='delete-user'),
    path('disable-user/<pk>', disable_user, name='disable-user'),
    path('delete-simple-topup/<int:pk>', delete_Stopup, name='deleteS'),
    path('delete-compound-topup/<int:pk>', delete_Ctopup, name='deleteC'),
    path('delete/<int:pk>', delete_order, name='delete'),
    path('edit', account_setting, name='edit'),
    path('update/<pk>', updateCustomer, name='update_c'),
    ]